---
- hosts: localhost
  
  vars:
    bigip_pool_name: my-pool
    bigip_pool_member_replace_all: yes
    bigip_server_address: 192.168.122.5
    bigip_admin: admin
    bigip_admin_password: secret
    bigip_pool_member_aggregate: ""
      
  tasks:
     #- name: set facts
     #  set_fact:
      #  bigip_pool_member_aggregate: "{{ bigip_pool_member_aggregate | to_json }}"
     - name: Add pool members aggregate, remove non aggregates
       bigip_pool_member:
        pool: "{{ bigip_pool_name }}"
        aggregate: "{{ bigip_pool_member_aggregate }}"
        replace_all_with: "{{ bigip_pool_member_replace_all }}"
        provider:
         server: "{{ bigip_server_address }}"
         user: "{{ bigip_admin }}"
         password: "{{ bigip_admin_password }}"    